# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

dryRun: false

secretName: gitlab-reporter

image: "quay.io/ukhomeofficedigital/acp-gitlab-reporting:v1.0.0"

schedule: "0 5 * * *"

name: gitlab-reporter
